version: "3.9"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      IP_ADDR: ${IP_ADDR}
    restart:
      unless-stopped
    depends_on:
      - django
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  django:
    build: ./honey
    container_name: django
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - IP_ADDR=${IP_ADDR}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 honey.asgi:application"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: