version: "3.9"

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: honey-db
    environment:
      IP_ADDR: ${IP_ADDR}
      SECRET_KEY: ${DJANGO_SECRET_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      
  django:
    build: .
    container_name: honey-django
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: honey.settings.production
    depends_on:
      - db

